#!/bin/bash

. smoke.sh

smoke_url_ok "https://dealerplatform.demo.de.ivendi.com/de/api/stockmodule/health"
smoke_url_ok "https://dealerplatform.demo.de.ivendi.com/api/webshops/ping"
smoke_url_ok "https://dealerplatform.demo.de.ivendi.com/api/dealership-directory/ping"
smoke_url_ok "https://dealerplatform.demo.de.ivendi.com/uk/api/webshops/platform-plugin/ping"
smoke_url_ok "https://dealerplatform.demo.de.ivendi.com/uk/api/webshops/dealership-directory/ping"
smoke_url_ok "https://dealerplatform.demo.de.ivendi.com/v2/quoteware/ping"
smoke_url_ok "https://dealerplatform.demo.de.ivendi.com/platform/v2/ping"
smoke_url_ok "https://dealerplatform.demo.de.ivendi.com/dealer/platform"
smoke_url_ok "https://dealerplatform.demo.de.ivendi.com/apps/webshops/main.js"
smoke_url_ok "https://dealerplatform.demo.de.ivendi.com/uk/apps/webshops/dealership-directory/main.js"
smoke_url_ok "https://dealerplatform.demo.de.ivendi.com/apps/dealership-directory/main.js"
smoke_url_ok "https://dealerplatform.demo.de.ivendi.com/uk/apps/webshops/platform-plugin/main.js"
smoke_url_ok "https://webshops.demo.de.newvehicle.com/api/ping"
smoke_url_ok "https://webshops.demo.de.newvehicle.com/widgetapi/ping"
smoke_url_ok "https://webshops.demo.de.newvehicle.com/widget/i"
smoke_url_ok "https://webshops.demo.de.newvehicle.com/bootstrapper/i"
smoke_url_ok "https://webshops.demo.de.newvehicle.com/themebuilder/i"
smoke_url_ok "https://demo.de.newvehicle.com/iam"
smoke_url_ok "https://demo.de.newvehicle.com/api/ping"
smoke_url_ok "https://demo.de.newvehicle.com/platform/v2/ping"
smoke_url_ok "https://demo.de.newvehicle.com/public-platform/v2/ping"
smoke_url_ok "https://demo.de.newvehicle.com/quoteware/ping"
smoke_url_ok "https://demo.de.newvehicle.com/api/theming/themes/api/ping"
smoke_url_ok "https://webshops-admin.demo.de.newvehicle.com/platform/v2/ping"
smoke_url_ok "https://webshops-admin.demo.de.newvehicle.com/api/webshops/ping"
smoke_url_ok "https://webshops-admin.demo.de.newvehicle.com/api/dealership-directory/ping"
smoke_url_ok "https://webshops-admin.demo.de.newvehicle.com/uk/api/webshops/platform-plugin/ping"
smoke_url_ok "https://webshops-admin.demo.de.newvehicle.com/uk/api/webshops/dealership-directory/ping"
smoke_url_ok "https://webshops-admin.demo.de.newvehicle.com/apps/webshops/main.js"
smoke_url_ok "https://webshops-admin.demo.de.newvehicle.com/uk/apps/webshops/dealership-directory/main.js"
smoke_url_ok "https://webshops-admin.demo.de.newvehicle.com/apps/dealership-directory/main.js"
smoke_url_ok "https://webshops-admin.demo.de.newvehicle.com/uk/apps/webshops/platform-plugin/main.js"
smoke_url_ok "https://my.demo.de.newvehicle.com/iam"
smoke_url_ok "https://my.demo.de.newvehicle.com/platform/v2/ping"
smoke_url_ok "https://my.demo.de.newvehicle.com/quoteware/ping"
smoke_url_ok "https://my.demo.de.newvehicle.com/api/ping"
smoke_url_ok "https://my.demo.de.newvehicle.com/api/theming/themes/api/ping"
smoke_url_ok "https://my.demo.de.newvehicle.com/api/webshops/ping"
smoke_url_ok "https://my.demo.de.newvehicle.com/api/dealership-directory/ping"
smoke_url_ok "https://my.demo.de.newvehicle.com/uk/api/webshops/platform-plugin/ping"
smoke_url_ok "https://my.demo.de.newvehicle.com/uk/api/webshops/dealership-directory/ping"
smoke_url_ok "https://my.demo.de.newvehicle.com/apps/webshops/main.js"
smoke_url_ok "https://my.demo.de.newvehicle.com/uk/apps/webshops/dealership-directory/main.js"
smoke_url_ok "https://my.demo.de.newvehicle.com/apps/dealership-directory/main.js"
smoke_url_ok "https://my.demo.de.newvehicle.com/uk/apps/webshops/platform-plugin/main.js"
smoke_url_ok "https://qw3.demo.de.ivendi.com/ping"
smoke_url_ok "https://qw3.demo.de.ivendi.com/adminapi/health"
smoke_url_ok "https://aaf.webshops-demo.de.newvehicle.com/quoteware/ping"
smoke_url_ok "https://aaf.webshops-demo.de.newvehicle.com/widgets/Webshop"

smoke_report